# Generated by Django 5.2.17 on 2026-08-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدم'), ('under_processing', 'قيد المراجعة'), ('approved', 'مجاز'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='الحالة')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقديم')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
                'permissions': [('can_submit', 'يمكنه تقديم الطلبات'), ('can_review', 'يمكنه مراجعة الطلبات (قيد المراجعة)'), ('can_approve', 'يمكنه اعتماد الطلبات'), ('can_reject', 'يمكنه رفض الطلبات')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='اسم المرفق')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='الملف')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, help_text='مثال: معدات المناجم', max_length=200, verbose_name='التصنيف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'بند تفصيلي',
                'verbose_name_plural': 'البنود التفصيلية',
                'ordering': ['application', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDetailField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='الحقل')),
                ('value', models.TextField(blank=True, verbose_name='القيمة')),
            ],
            options={
                'verbose_name': 'خلية تفصيلية',
                'verbose_name_plural': 'الخلايا التفصيلية',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='الحقل')),
                ('value', models.TextField(blank=True, verbose_name='القيمة')),
            ],
            options={
                'verbose_name': 'حقل استمارة',
                'verbose_name_plural': 'حقول الاستمارة',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(choices=[('exploration', 'استكشاف'), ('production', 'إنتاج'), ('tailings', 'مخلفات'), ('small', 'صغير')], max_length=20, verbose_name='نوع الشركة')),
                ('url_name', models.SlugField(max_length=100, verbose_name='اسم الرابط')),
                ('model_name', models.CharField(max_length=100, verbose_name='اسم الموديل')),
                ('verbose_name', models.CharField(max_length=200, verbose_name='الاسم الإنجليزي')),
                ('arabic_name', models.CharField(max_length=200, verbose_name='الاسم العربي')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('form_fields', models.JSONField(blank=True, default=list, verbose_name='حقول الاستمارة')),
                ('field_specs', models.JSONField(blank=True, default=dict, help_text='مثال: {"الغرض من التصديق": {"type": "select", "choices": ["خيار1", "خيار2"]}} الأنواع المتاحة: select / integer / float / decimal', verbose_name='مواصفات الحقول')),
                ('detail_models', models.JSONField(blank=True, default=list, verbose_name='نماذج التفاصيل')),
                ('detail_fields', models.JSONField(blank=True, default=list, verbose_name='حقول التفاصيل')),
                ('detail_specs', models.JSONField(blank=True, default=dict, help_text='مثال: {"وزن العينة": {"type": "float"}} — الأنواع المتاحة: select / integer / float / decimal', verbose_name='مواصفات حقول التفاصيل')),
                ('field_layout', models.JSONField(blank=True, default=dict, help_text='مثال: {"columns": 2, "attachment_columns": 2, "groups": [{"title": "بيانات", "fields": ["حقل1", "حقل2"]}]} — columns: عدد أعمدة الحقول، attachment_columns: عدد أعمدة المرفقات، groups: مجموعات بعناوين (الترتيب حسب المجموعات)', verbose_name='تخطيط الحقول')),
                ('event_category', models.CharField(blank=True, choices=[('legal', 'قانوني'), ('financial', 'مالي'), ('technical', 'فني')], max_length=20, null=True, verbose_name='تصنيف الحدث التاريخي')),
                ('event_label', models.CharField(blank=True, max_length=100, verbose_name='نوع الحدث التاريخي')),
            ],
            options={
                'verbose_name': 'نوع الطلب / الإجراء',
                'verbose_name_plural': 'أنواع الطلبات / الإجراءات',
                'ordering': ['company_type', 'arabic_name'],
            },
        ),
    ]
