# Generated by Django 5.2.17 on 2026-08-17 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='companies.agreement', verbose_name='الاتفاقية / العقد'),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='المراجع'),
        ),
        migrations.AddField(
            model_name='application',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_applications', to=settings.AUTH_USER_MODEL, verbose_name='مقدّم الطلب'),
        ),
        migrations.AddField(
            model_name='applicationattachment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='applications.application', verbose_name='الطلب'),
        ),
        migrations.AddField(
            model_name='applicationdetail',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='applications.application', verbose_name='الطلب'),
        ),
        migrations.AddField(
            model_name='applicationdetailfield',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='applications.applicationdetail', verbose_name='البند التفصيلي'),
        ),
        migrations.AddField(
            model_name='applicationfield',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='applications.application', verbose_name='الطلب'),
        ),
        migrations.AddConstraint(
            model_name='applicationtype',
            constraint=models.UniqueConstraint(fields=('company_type', 'url_name'), name='unique_app_type_per_company_type'),
        ),
        migrations.AddField(
            model_name='application',
            name='app_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.applicationtype', verbose_name='نوع الطلب'),
        ),
    ]
