# Generated by Django 5.2.17 on 2026-08-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtype',
            name='contract_types',
            field=models.JSONField(blank=True, default=list, help_text='أنواع العقد المسموح لهذا الطلب، مثال: ["mining", "two_minerals"] — فارغ = غير مقيد', verbose_name='أنواع العقود المسموحة'),
        ),
    ]
