# Generated by Django 5.2.17 on 2026-08-17 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicationtype_contract_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'permissions': [('can_submit', 'يمكنه تأكيد الطلبات'), ('can_review', 'يمكنه مراجعة الطلبات (قيد المراجعة)'), ('can_approve', 'يمكنه اعتماد الطلبات'), ('can_reject', 'يمكنه رفض الطلبات')], 'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مؤكد'), ('under_processing', 'قيد المراجعة'), ('approved', 'مجاز'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='application',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد'),
        ),
        migrations.AlterField(
            model_name='application',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_applications', to=settings.AUTH_USER_MODEL, verbose_name='مؤكّد الطلب'),
        ),
    ]
