# Generated by Django 5.2.17 on 2026-08-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_options_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtype',
            name='detail_specs',
            field=models.JSONField(blank=True, default=dict, help_text='مثال: {"وزن العينة": {"type": "float"}} — الأنواع المتاحة: select / integer / float / decimal؛ "required": true يجعل العمود إلزامياً', verbose_name='مواصفات حقول التفاصيل'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='field_specs',
            field=models.JSONField(blank=True, default=dict, help_text='مثال: {"الغرض من التصديق": {"type": "select", "choices": ["خيار1", "خيار2"]}} — الأنواع المتاحة: select / integer / float / decimal؛ "required": true يجعل الحقل إلزامياً (افتراضياً اختياري)', verbose_name='مواصفات الحقول'),
        ),
    ]
