# Generated by Django 5.2.17 on 2026-08-17 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_applicationtype_detail_specs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'مسودة'), ('submitted', 'مؤكد'), ('under_processing', 'قيد المراجعة'), ('approved', 'مجاز'), ('rejected', 'مرفوض')], max_length=20, null=True, verbose_name='من الحالة')),
                ('to_status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مؤكد'), ('under_processing', 'قيد المراجعة'), ('approved', 'مجاز'), ('rejected', 'مرفوض')], max_length=20, verbose_name='إلى الحالة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='applications.application', verbose_name='الطلب')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تحول حالة الطلب',
                'verbose_name_plural': 'تحولات حالة الطلبات',
                'ordering': ['application', 'timestamp', 'id'],
            },
        ),
    ]
