# Generated by Django 5.2.17 on 2026-08-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_applicationtransition'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtransition',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='الوقت الذي قضاه الطلب في from_status قبل هذا التحول (فارغ للإنشاء).', null=True, verbose_name='المدة في الحالة (ثانية)'),
        ),
    ]
