# Generated by Django 5.2.17 on 2026-08-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_applicationtransition_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtransition',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='الوقت (بالثواني) الذي قضاه الطلب في from_status قبل هذا التحول، محسوباً على أساس ساعات العمل فقط (الأحد-الخميس 08:00-16:00) — فارغ للإنشاء.', null=True, verbose_name='المدة في الحالة (ساعات العمل)'),
        ),
    ]
