# Generated by Django 5.2.17 on 2026-08-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_applicationtransition_duration_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHoursSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('start_date', models.DateField(verbose_name='بداية السريان')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='نهاية السريان')),
                ('work_start', models.TimeField(verbose_name='بداية الدوام')),
                ('work_end', models.TimeField(verbose_name='نهاية الدوام')),
                ('working_weekdays', models.JSONField(blank=True, default=list, verbose_name='أيام العمل')),
            ],
            options={
                'verbose_name': 'جدول ساعات العمل',
                'verbose_name_plural': 'جداول ساعات العمل',
                'ordering': ['start_date'],
            },
        ),
    ]
