# Generated by Django 5.2.17 on 2026-08-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_workinghoursschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'permissions': [('can_submit', 'يمكنه تأكيد الطلبات'), ('can_review', 'يمكنه مراجعة الطلبات (قيد المعالجة)'), ('can_approve', 'يمكنه اعتماد الطلبات'), ('can_reject', 'يمكنه رفض الطلبات')], 'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مؤكد'), ('under_processing', 'قيد المعالجة'), ('approved', 'مجاز'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='applicationtransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('draft', 'مسودة'), ('submitted', 'مؤكد'), ('under_processing', 'قيد المعالجة'), ('approved', 'مجاز'), ('rejected', 'مرفوض')], max_length=20, null=True, verbose_name='من الحالة'),
        ),
        migrations.AlterField(
            model_name='applicationtransition',
            name='to_status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مؤكد'), ('under_processing', 'قيد المعالجة'), ('approved', 'مجاز'), ('rejected', 'مرفوض')], max_length=20, verbose_name='إلى الحالة'),
        ),
    ]
