# Generated by Django 5.2.17 on 2026-08-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_application_options_alter_application_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationtype',
            name='unique_app_type_per_company_type',
        ),
        migrations.RemoveField(
            model_name='applicationtype',
            name='url_name',
        ),
        migrations.AddConstraint(
            model_name='applicationtype',
            constraint=models.UniqueConstraint(fields=('company_type', 'model_name'), name='unique_app_type_per_company_type'),
        ),
    ]
