# Generated by Django 5.2.17 on 2026-08-18 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_remove_applicationtype_unique_app_type_per_company_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'permissions': [('can_submit', 'يمكنه تأكيد الطلبات'), ('can_review', 'يمكنه مراجعة الطلبات (قيد المعالجة)'), ('can_committee_recommend', 'يمكنه تقديم توصية اللجنة'), ('can_undersecretary_recommend', 'يمكنه تقديم توصية وكيل الوزارة'), ('can_approve', 'يمكنه اعتماد الطلبات'), ('can_reject', 'يمكنه رفض الطلبات')], 'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AddField(
            model_name='application',
            name='committee_recommendation',
            field=models.CharField(blank=True, choices=[('recommended', 'موصى به'), ('not_recommended', 'غير موصى به')], max_length=20, null=True, verbose_name='توصية اللجنة'),
        ),
        migrations.AddField(
            model_name='application',
            name='committee_recommendation_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات توصية اللجنة'),
        ),
        migrations.AddField(
            model_name='application',
            name='committee_recommended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ توصية اللجنة'),
        ),
        migrations.AddField(
            model_name='application',
            name='committee_recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_recommended_applications', to=settings.AUTH_USER_MODEL, verbose_name='مقدم توصية اللجنة'),
        ),
        migrations.AddField(
            model_name='application',
            name='undersecretary_recommendation',
            field=models.CharField(blank=True, choices=[('recommended', 'موصى به'), ('not_recommended', 'غير موصى به')], max_length=20, null=True, verbose_name='توصية وكيل الوزارة'),
        ),
        migrations.AddField(
            model_name='application',
            name='undersecretary_recommendation_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات توصية وكيل الوزارة'),
        ),
        migrations.AddField(
            model_name='application',
            name='undersecretary_recommended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ توصية وكيل الوزارة'),
        ),
        migrations.AddField(
            model_name='application',
            name='undersecretary_recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undersecretary_recommended_applications', to=settings.AUTH_USER_MODEL, verbose_name='مقدم توصية وكيل الوزارة'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مؤكد'), ('under_processing', 'قيد المعالجة'), ('committee_recommendation', 'توصية اللجنة'), ('undersecretary_recommendation', 'توصية وكيل الوزارة'), ('approved', 'مجاز'), ('rejected', 'مرفوض')], default='draft', max_length=32, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='applicationtransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('draft', 'مسودة'), ('submitted', 'مؤكد'), ('under_processing', 'قيد المعالجة'), ('committee_recommendation', 'توصية اللجنة'), ('undersecretary_recommendation', 'توصية وكيل الوزارة'), ('approved', 'مجاز'), ('rejected', 'مرفوض')], max_length=32, null=True, verbose_name='من الحالة'),
        ),
        migrations.AlterField(
            model_name='applicationtransition',
            name='to_status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مؤكد'), ('under_processing', 'قيد المعالجة'), ('committee_recommendation', 'توصية اللجنة'), ('undersecretary_recommendation', 'توصية وكيل الوزارة'), ('approved', 'مجاز'), ('rejected', 'مرفوض')], max_length=32, verbose_name='إلى الحالة'),
        ),
    ]
