# Generated by Django 5.2.17 on 2026-08-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='minister_decision',
            field=models.TextField(blank=True, verbose_name='قرار الوزير'),
        ),
    ]
