# Generated by Django 5.2.17 on 2026-10-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_application_minister_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مؤكد'), ('under_processing', 'قيد المعالجة'), ('committee_recommendation', 'توصية اللجنة'), ('undersecretary_recommendation', 'توصية وكيل الوزارة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='draft', max_length=32, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='applicationtransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('draft', 'مسودة'), ('submitted', 'مؤكد'), ('under_processing', 'قيد المعالجة'), ('committee_recommendation', 'توصية اللجنة'), ('undersecretary_recommendation', 'توصية وكيل الوزارة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], max_length=32, null=True, verbose_name='من الحالة'),
        ),
        migrations.AlterField(
            model_name='applicationtransition',
            name='to_status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مؤكد'), ('under_processing', 'قيد المعالجة'), ('committee_recommendation', 'توصية اللجنة'), ('undersecretary_recommendation', 'توصية وكيل الوزارة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], max_length=32, verbose_name='إلى الحالة'),
        ),
    ]
