# Generated by Django 5.2.17 on 2026-08-17 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رمز المربع')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='اسم المربع')),
                ('coordinates', models.JSONField(blank=True, default=list, verbose_name='الإحداثيات')),
            ],
            options={
                'verbose_name': 'مربع',
                'verbose_name_plural': 'المربعات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم الشركة (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Company name (English)')),
                ('company_type', models.CharField(choices=[('exploration', 'استكشاف'), ('production', 'إنتاج'), ('tailings', 'مخلفات'), ('small', 'صغير')], default='exploration', max_length=20, verbose_name='نوع الشركة')),
                ('registration_no', models.CharField(blank=True, max_length=100, verbose_name='رقم التسجيل')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('general_status', models.CharField(choices=[('green', 'اخضر'), ('yellow', 'اصفر'), ('red', 'احمر')], default='green', max_length=10, verbose_name='حالة الشركة العامة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم المحلية (عربي)')),
            ],
            options={
                'verbose_name': 'محلية',
                'verbose_name_plural': 'المحليات',
                'ordering': ['state', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='اسم المعدن')),
            ],
            options={
                'verbose_name': 'معدن',
                'verbose_name_plural': 'المعادن',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='اسم الولاية (عربي)')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='State name (English)')),
            ],
            options={
                'verbose_name': 'ولاية',
                'verbose_name_plural': 'الولايات',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('concession', 'امتياز'), ('mining', 'عقد تعدين'), ('tailings', 'مخلفات'), ('two_minerals', 'حجر معدنين'), ('preprocessed_tailings', 'مخلفات معالجة مسبقا'), ('small', 'صغير')], default='concession', max_length=40, verbose_name='نوع العقد')),
                ('area_name', models.CharField(blank=True, max_length=100, verbose_name='المنطقة')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('signing_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوقيع')),
                ('initial_area_km2', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='المساحة الأولية (كم2)')),
                ('current_area_km2', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='المساحة الحالية (كم2)')),
                ('validity_status', models.CharField(choices=[('active', 'ساري'), ('expired', 'منتهي'), ('frozen', 'مجمد'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='سريان الاتفاقية')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='companies.block', verbose_name='المربع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='companies.company', verbose_name='الشركة')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='companies.locality', verbose_name='المحلية')),
                ('mineral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='companies.mineral', verbose_name='المعدن')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='companies.state', verbose_name='الولاية')),
            ],
            options={
                'verbose_name': 'اتفاقية / عقد / رخصة',
                'verbose_name_plural': 'الاتفاقيات / العقود / الرخص',
                'ordering': ['company', '-signing_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('claim', 'مطالبة'), ('payment', 'سداد'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع الحدث')),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='المبلغ')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_events', to='companies.agreement', verbose_name='الاتفاقية / العقد')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='applications.application', verbose_name='الطلب المرتبط')),
            ],
            options={
                'verbose_name': 'حدث مالي (السرد التاريخي)',
                'verbose_name_plural': 'الأحداث المالية (السرد التاريخي)',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='المديونية')),
                ('current_claim', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='المطالبة الحالية')),
                ('contractual_claim', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='المطالبة المالية وفق العقد')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر سداد')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='الرصيد')),
                ('satisfied', models.BooleanField(default=False, help_text='محدد = مستوفي، غير محدد = غير مستوفي', verbose_name='مستوفي / غير مستوفي')),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_position', to='companies.agreement', verbose_name='الاتفاقية / العقد')),
            ],
            options={
                'verbose_name': 'الموقف المالي',
                'verbose_name_plural': 'المواقف المالية',
            },
        ),
        migrations.CreateModel(
            name='LegalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('extension', 'تمديد'), ('relinquishment', 'تنازل'), ('cancellation', 'إلغاء'), ('legal_warning', 'إنذار قانوني'), ('freeze', 'تجميد'), ('name_change', 'تغيير اسم'), ('area_change', 'تعديل مساحة'), ('no_renewal', 'عدم رغبة في التجديد'), ('other', 'أخرى')], default='other', max_length=30, verbose_name='نوع الحدث')),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_events', to='companies.agreement', verbose_name='الاتفاقية / العقد')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='applications.application', verbose_name='الطلب المرتبط')),
            ],
            options={
                'verbose_name': 'حدث قانوني (السرد التاريخي)',
                'verbose_name_plural': 'الأحداث القانونية (السرد التاريخي)',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='locality',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localities', to='companies.state', verbose_name='الولاية'),
        ),
        migrations.CreateModel(
            name='TechnicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('remote_sensing', 'دراسات استشعار عن بعد'), ('sampling', 'جمع وفحص عينات'), ('survey', 'مسح طبوغرافي/جيوفيزيائي'), ('trenching', 'حفر ترنشات'), ('work_plan', 'خطة عمل'), ('study', 'دراسة جدوى'), ('report', 'تقرير فني ومالي'), ('production', 'إنتاج'), ('export', 'صادر'), ('mining_design', 'تصميم المنجم'), ('plant_capacity', 'الطاقة التصميمية للمصنع'), ('technical_issues', 'المشاكل الفنية/الايجابيات'), ('other', 'أخرى')], default='other', max_length=30, verbose_name='نوع الحدث')),
                ('category', models.CharField(blank=True, help_text='مثال: عقد التعدين / عقد المخلقات / عقد حجر المعدنين', max_length=100, verbose_name='التصنيف')),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_events', to='companies.agreement', verbose_name='الاتفاقية / العقد')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='applications.application', verbose_name='الطلب المرتبط')),
            ],
            options={
                'verbose_name': 'حدث فني (السرد التاريخي للأعمال الفنية)',
                'verbose_name_plural': 'الأحداث الفنية (السرد التاريخي للأعمال الفنية)',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_program', models.TextField(blank=True, verbose_name='برنامج العمل')),
                ('budget', models.TextField(blank=True, verbose_name='الموازنة')),
                ('work_method', models.TextField(blank=True, verbose_name='طريقة العمل')),
                ('tech_financial_reports', models.TextField(blank=True, verbose_name='التقارير الفنية والمالية')),
                ('field_status', models.TextField(blank=True, verbose_name='الموقف بالحقل')),
                ('production_status', models.TextField(blank=True, verbose_name='الموقف الانتاجي')),
                ('activity_summary', models.TextField(blank=True, verbose_name='ملخص النشاط الفني')),
                ('work_plan_approval_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إجازة خطة العمل')),
                ('processing_method', models.CharField(blank=True, help_text='VAT / CIL / Heap Leaching', max_length=100, verbose_name='طريقة المعالجة')),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_position', to='companies.agreement', verbose_name='الاتفاقية / العقد')),
            ],
            options={
                'verbose_name': 'الموقف الفني',
                'verbose_name_plural': 'المواقف الفنية',
            },
        ),
        migrations.AddConstraint(
            model_name='locality',
            constraint=models.UniqueConstraint(fields=('state', 'name_ar'), name='unique_locality_per_state'),
        ),
    ]
