# Generated by Django 5.2.17 on 2026-08-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='agreement_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم الاتفاقية/العقد'),
        ),
        migrations.AddField(
            model_name='company',
            name='manager_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المدير'),
        ),
        migrations.AddField(
            model_name='company',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='هاتف المدير'),
        ),
        migrations.AddField(
            model_name='company',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='الجنسية'),
        ),
        migrations.AddField(
            model_name='company',
            name='rep_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الممثل'),
        ),
        migrations.AddField(
            model_name='company',
            name='rep_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='هاتف الممثل'),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=300, verbose_name='الموقع الإلكتروني'),
        ),
    ]
