# Generated by Django 5.2.17 on 2026-08-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_agreement_agreement_no_company_manager_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
    ]
