# Generated by Django 5.2.17 on 2026-08-17 14:29

from django.db import migrations, models


def create_nationalities_and_link(apps, schema_editor):
    Nationality = apps.get_model("companies", "Nationality")
    Company = apps.get_model("companies", "Company")
    for company in Company.objects.all().iterator():
        raw = company.nationality or ""
        codes = [part.strip() for part in raw.split(",") if part.strip()]
        for code in codes:
            nationality, _ = Nationality.objects.get_or_create(
                code=code, defaults={"name_ar": code}
            )
            company.nationalities.add(nationality)


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_agreement_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="الرمز")),
                (
                    "name_ar",
                    models.CharField(blank=True, max_length=100, verbose_name="اسم الجنسية (عربي)"),
                ),
            ],
            options={
                "verbose_name": "جنسية",
                "verbose_name_plural": "الجنسيات",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="company",
            name="nationalities",
            field=models.ManyToManyField(
                blank=True,
                related_name="companies",
                to="companies.nationality",
                verbose_name="الجنسيات",
            ),
        ),
        migrations.RunPython(create_nationalities_and_link, migrations.RunPython.noop),
        migrations.RemoveField(model_name="company", name="status"),
        migrations.RemoveField(model_name="company", name="nationality"),
    ]
