# Generated by Django 5.2.17 on 2026-08-17 14:36

import re

from django.db import migrations, models

MINERAL_NORMALIZE = {
    "الذهب": "ذهب",
    "النحاس": "نحاس",
    "الكروم": "كروم",
    "الحديد": "حديد",
    "المنجنيز": "منجنيز",
    "الرخام": "رخام",
    "الجبس": "جبس",
    "جبص": "جبس",
    "الملح": "ملح",
    "الفضة": "فضة",
}


def relink_minerals(apps, schema_editor):
    Agreement = apps.get_model("companies", "Agreement")
    Mineral = apps.get_model("companies", "Mineral")
    for agreement in Agreement.objects.exclude(mineral__isnull=True).iterator():
        name = agreement.mineral.name_ar
        parts = [part.strip() for part in re.split(r"[،,]", name or "") if part.strip()]
        parts = list(dict.fromkeys(MINERAL_NORMALIZE.get(p, p) for p in parts))
        for part in parts:
            mineral, _ = Mineral.objects.get_or_create(name_ar=part)
            agreement.minerals.add(mineral)
    # Remove lookup rows that only existed because of combined/ب forms.
    for mineral in Mineral.objects.all():
        if mineral.agreements.count() == 0 and (
            "," in (mineral.name_ar or "") or mineral.name_ar in MINERAL_NORMALIZE
        ):
            mineral.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_auto_20260817_1629"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="minerals",
            field=models.ManyToManyField(
                blank=True, related_name="agreements", to="companies.mineral", verbose_name="المعادن"
            ),
        ),
        migrations.RunPython(relink_minerals, migrations.RunPython.noop),
        migrations.RemoveField(model_name="agreement", name="mineral"),
    ]
