# Generated by Django 5.2.17 on 2026-08-17 14:40

from django.db import migrations


def clean_mineral_lookup(apps, schema_editor):
    Mineral = apps.get_model("companies", "Mineral")
    for mineral in Mineral.objects.all():
        name = mineral.name_ar or ""
        is_combined = "،" in name or "," in name
        is_variant = name in {
            "الذهب", "النحاس", "الكروم", "الحديد", "المنجنيز", "الرخام",
            "الجبس", "جبص", "الملح", "الفضة", "الجرانيت",
        }
        if mineral.agreements.count() == 0 and (is_combined or is_variant):
            mineral.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_auto_20260817_1636"),
    ]

    operations = [
        migrations.RunPython(clean_mineral_lookup, migrations.RunPython.noop),
    ]
