# Generated by Django 5.2.17 on 2026-08-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_mineral_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='contract_type',
            field=models.CharField(choices=[('concession', 'إستكشاف'), ('mining', 'عقد تعدين'), ('tailings', 'مخلفات'), ('two_minerals', 'حجر معدنين'), ('preprocessed_tailings', 'مخلفات معالجة مسبقا'), ('small', 'صغير')], default='concession', max_length=40, verbose_name='نوع العقد'),
        ),
    ]
