# Generated by Django 5.2.17 on 2026-08-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
        ('companies', '0007_alter_agreement_contract_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogProxy',
            fields=[
            ],
            options={
                'verbose_name': 'سجل التدقيق',
                'verbose_name_plural': 'سجل التدقيق',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auditlog.logentry',),
        ),
    ]
